### ISSUE TITLE
can we add the impericog?

### ISSUE THREAD

**Issue by DarthMDev** [nate97/src#10]
If you dont know who he is this is him (he is the middle one)
https://i.ytimg.com/vi/27A6jkEbx-U/hqdefault.jpg?sqp=-oaymwEWCKgBEF5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLATeqBxUkk6FlaoU4DplkDuvlIodw

I think it be cool to add as a boss of some sort or a top tier cog of some sort as a new cog type

**Comment by nate97** [comment]
Again this is a project aimed at recreating the original Toontown Online, if you'd like to fork it and make your own tweaks, that's fine.
